Repository wi23b004/TicTacToeGame-GroupE, pull requests merged in 2024-06, with the labels that each got.

#1 Erstellung einer CI/CD-Pipeline
  .github/workflows/ci.yml
Labels: CI/CD

#3 Draft Pull Request: Implementierung der ersten zwei Unit-Tests
  checkstyle.xml
  pom.xml
  src/main/java/org/example/TicTacToe.java
  src/main/resources/configuration_1_3.dtd
  src/test/java/org/example/TicTacToeTest.java
Labels: enhancement

#8 Unittests für zugMachen() Methode implementiert
  src/test/java/org/example/TicTacToeTest.java
Labels: enhancement

#10 Feature/neues spiel starten
  .github/workflows/ci.yml
  src/main/java/org/example/TicTacToe.java
Labels: enhancement

#16 Board Class implementiert
  src/main/java/org/example/Board.java
Labels: enhancement

#17 ADD: Implement Board and Player classes, and update TicTacToe class
  src/main/java/org/example/Board.java
  src/main/java/org/example/TicTacToe.java
Labels: enhancement

#19 ADD: Implemented method to display the current game state
  src/main/java/org/example/TicTacToe.java
Labels: enhancement

#29 Bugfix/notify-end-game
  src/main/java/org/example/Board.java
  src/main/java/org/example/TicTacToe.java
Labels: bug

#34 Cleanup/compact methods
  .github/workflows/ci.yml
  src/main/java/org/example/Board.java
  src/main/java/org/example/TicTacToe.java
Labels: enhancement
